package model;
// Generated Dec 10, 2021 8:51:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Admin generated by hbm2java
 */
public class Admin  implements java.io.Serializable {


     private String aid;
     private String password;
     private String fullname;
     private String email;
     private Set issues = new HashSet(0);
     private Set returnses = new HashSet(0);

    public Admin() {
    }

	
    public Admin(String aid, String password, String fullname, String email) {
        this.aid = aid;
        this.password = password;
        this.fullname = fullname;
        this.email = email;
    }
    public Admin(String aid, String password, String fullname, String email, Set issues, Set returnses) {
       this.aid = aid;
       this.password = password;
       this.fullname = fullname;
       this.email = email;
       this.issues = issues;
       this.returnses = returnses;
    }
   
    public String getAid() {
        return this.aid;
    }
    
    public void setAid(String aid) {
        this.aid = aid;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getIssues() {
        return this.issues;
    }
    
    public void setIssues(Set issues) {
        this.issues = issues;
    }
    public Set getReturnses() {
        return this.returnses;
    }
    
    public void setReturnses(Set returnses) {
        this.returnses = returnses;
    }




}


