package model;
// Generated Dec 18, 2021 12:55:07 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Books generated by hbm2java
 */
public class Books  implements java.io.Serializable {


     private Integer id;
     private Category category;
     private Publisher publisher;
     private String name;
     private int status;
     private String description;
     private String image;
     private Set issues = new HashSet(0);

    public Books() {
    }

	
    public Books(Category category, Publisher publisher, String name, int status) {
        this.category = category;
        this.publisher = publisher;
        this.name = name;
        this.status = status;
    }
    public Books(Category category, Publisher publisher, String name, int status, String description, String image, Set issues) {
       this.category = category;
       this.publisher = publisher;
       this.name = name;
       this.status = status;
       this.description = description;
       this.image = image;
       this.issues = issues;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public Publisher getPublisher() {
        return this.publisher;
    }
    
    public void setPublisher(Publisher publisher) {
        this.publisher = publisher;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public Set getIssues() {
        return this.issues;
    }
    
    public void setIssues(Set issues) {
        this.issues = issues;
    }




}


