package model;
// Generated Dec 10, 2021 8:51:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private Integer cid;
     private String cname;
     private Set bookses = new HashSet(0);

    public Category() {
    }

	
    public Category(String cname) {
        this.cname = cname;
    }
    public Category(String cname, Set bookses) {
       this.cname = cname;
       this.bookses = bookses;
    }
   
    public Integer getCid() {
        return this.cid;
    }
    
    public void setCid(Integer cid) {
        this.cid = cid;
    }
    public String getCname() {
        return this.cname;
    }
    
    public void setCname(String cname) {
        this.cname = cname;
    }
    public Set getBookses() {
        return this.bookses;
    }
    
    public void setBookses(Set bookses) {
        this.bookses = bookses;
    }




}


