package model;
// Generated Dec 18, 2021 12:55:07 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Issue generated by hbm2java
 */
public class Issue  implements java.io.Serializable {


     private Integer id;
     private Admin admin;
     private Books books;
     private Students students;
     private int date;
     private int status;
     private Set returnses = new HashSet(0);

    public Issue() {
    }

	
    public Issue(Admin admin, Books books, Students students, int date, int status) {
        this.admin = admin;
        this.books = books;
        this.students = students;
        this.date = date;
        this.status = status;
    }
    public Issue(Admin admin, Books books, Students students, int date, int status, Set returnses) {
       this.admin = admin;
       this.books = books;
       this.students = students;
       this.date = date;
       this.status = status;
       this.returnses = returnses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Admin getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(Admin admin) {
        this.admin = admin;
    }
    public Books getBooks() {
        return this.books;
    }
    
    public void setBooks(Books books) {
        this.books = books;
    }
    public Students getStudents() {
        return this.students;
    }
    
    public void setStudents(Students students) {
        this.students = students;
    }
    public int getDate() {
        return this.date;
    }
    
    public void setDate(int date) {
        this.date = date;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public Set getReturnses() {
        return this.returnses;
    }
    
    public void setReturnses(Set returnses) {
        this.returnses = returnses;
    }




}


