package model;
// Generated Dec 10, 2021 8:51:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Publisher generated by hbm2java
 */
public class Publisher  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set bookses = new HashSet(0);

    public Publisher() {
    }

	
    public Publisher(String name) {
        this.name = name;
    }
    public Publisher(String name, Set bookses) {
       this.name = name;
       this.bookses = bookses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getBookses() {
        return this.bookses;
    }
    
    public void setBookses(Set bookses) {
        this.bookses = bookses;
    }




}


