package model;
// Generated Dec 18, 2021 12:55:07 AM by Hibernate Tools 4.3.1



/**
 * Returns generated by hbm2java
 */
public class Returns  implements java.io.Serializable {


     private Integer id;
     private Admin admin;
     private Issue issue;
     private Students students;
     private int date;

    public Returns() {
    }

    public Returns(Admin admin, Issue issue, Students students, int date) {
       this.admin = admin;
       this.issue = issue;
       this.students = students;
       this.date = date;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Admin getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(Admin admin) {
        this.admin = admin;
    }
    public Issue getIssue() {
        return this.issue;
    }
    
    public void setIssue(Issue issue) {
        this.issue = issue;
    }
    public Students getStudents() {
        return this.students;
    }
    
    public void setStudents(Students students) {
        this.students = students;
    }
    public int getDate() {
        return this.date;
    }
    
    public void setDate(int date) {
        this.date = date;
    }




}


